#!/usr/bin/env python3
"""Generate PamPan's browser portal and shared navigation blocks."""
from pathlib import Path
import html
import re

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
EXCLUDE = {"templates"}

def rel(source: Path, target: Path) -> str:
    return Path(__import__("os").path.relpath(target, source.parent)).as_posix()

def nav_for(path: Path) -> str:
    links = [(ROOT / "index.html", "Portal"), (ROOT / "README.md", "README"),
             (ROOT / "docs" / "README.md", "Docs guide"),
             (ROOT / "docs" / "reference" / "system-overview.html", "System overview"),
             (ROOT / "docs" / "reference" / "startup-and-verification.html", "Verification"),
             (ROOT / "docs" / "handover" / "current.html", "Current handover"),
             (ROOT / "docs" / "handover" / "changelog.html", "Changelog")]
    body = " · ".join(f'<a href="{html.escape(rel(path, target))}">{label}</a>' for target, label in links)
    return f'<nav class="doc-nav" aria-label="Documentation">{body}</nav>'

def tree(paths):
    root = {}
    for path in paths:
        node = root
        for part in path.parts:
            node = node.setdefault(part, {})
    def render(node):
        bits = []
        for name, children in sorted(node.items()):
            if children:
                bits.append(f"<details><summary>{html.escape(name)}/</summary>{render(children)}</details>")
            else:
                href = html.escape(name)
                bits.append(f'<div><a href="{href}">{html.escape(name)}</a></div>')
        return "<div>" + "".join(bits) + "</div>"
    # Tree links need repository-relative rather than leaf names.
    def render_at(node, prefix=Path()):
        bits=[]
        for name, children in sorted(node.items()):
            here=prefix / name
            if children: bits.append(f"<details><summary>{html.escape(name)}/</summary>{render_at(children, here)}</details>")
            else: bits.append(f'<div><a href="{html.escape(here.as_posix())}">{html.escape(name)}</a></div>')
        return "<div>"+"".join(bits)+"</div>"
    return render_at(root)

def main():
    documents = sorted(p for p in DOCS.rglob("*.html") if not any(part in EXCLUDE for part in p.relative_to(DOCS).parts))
    marker = re.compile(r"<!-- DOC-NAV:START -->.*?<!-- DOC-NAV:END -->", re.S)
    for path in documents:
        content = path.read_text()
        replacement = "<!-- DOC-NAV:START -->" + nav_for(path) + "<!-- DOC-NAV:END -->"
        if not marker.search(content):
            raise SystemExit(f"missing navigation markers: {path.relative_to(ROOT)}")
        path.write_text(marker.sub(replacement, content))
    portal_paths = [Path("README.md"), Path("AGENTS.md")]
    portal_paths += [p.relative_to(ROOT) for p in sorted(DOCS.rglob("*")) if p.is_file()]
    portal_paths += [p.relative_to(ROOT) for p in sorted((ROOT / "scripts").glob("*.py"))]
    portal = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>PamPan documentation portal</title>
  <link rel="stylesheet" href="docs/assets/docs-style.css">
</head>
<body>
  <main>
    <section class="portal">
      <h1>PamPan documentation portal</h1>
      <p class="muted">Generated by scripts/update-doc-navigation.py. Folders are collapsed by default.</p>
      {tree(portal_paths)}
    </section>
  </main>
</body>
</html>
'''
    (ROOT / "index.html").write_text(portal)

if __name__ == "__main__": main()
